language: java
jdk:
- openjdk11

branches:
  only:
  - master
  - develop
  - "/^v[0-9]+\\.[0-9]+/"

before_install:
- echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
- echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

after_success:
- test "${TRAVIS_PULL_REQUEST}" == "false" && test "${TRAVIS_TAG}" != "" -o "${TRAVIS_BRANCH}" == "master" && mvn deploy -P release --settings travis-settings.xml

cache:
  directories:
    - '$HOME/.m2/repository'
